### ISSUE TITLE
lost tokens from unstaking bug

### ISSUE THREAD

**Issue by dynsky** [manifoldfinance/support#4]
user has lost access to tokens after unstaking tokens on dapp
1) 250 XFOLD
https://etherscan.io/tx/0x21772026048c5930e113f9a206a7eed5733613ffad1152ebd7fd12ce7d2a1b8b

2) 296.16 XFOLD
https://etherscan.io/tx/0x3f7bbd061602a5fc598e7ad68d55fce31c3a06197c52716ce6ab0d9195dc5ea9

**Comment by sambacha** [comment]
How? 

We are not covering this sort of issue without more details, please provide context such as OS, Browser, wallet provider, etc

**Comment by dynsky** [comment]
windows 10, chrome, metamask. fold tokens were send to manifold contract address instead to wallet that burned xfold using dapp
i thought details are not needed as it is known issue and some people who lost due to it were reimbursed

**Comment by sambacha** [comment]
> windows 10, chrome, metamask. fold tokens were send to manifold contract address instead to wallet that burned xfold using dapp i thought details are not needed as it is known issue and some people who lost due to it were reimbursed

this issue has been fixed awhile ago

**Comment by dynsky** [comment]
https://github.com/manifoldfinance/staking/commit/ae1cc092f3ab8b673bfe827b5ac5b7b40190c799
it was commited on january 1 and transactions that i provided are from december 24. are they applicable for reimbursement?

**Comment by sambacha** [comment]
yes will look into this thanks for following up @dynsky

**Comment by dynsky** [comment]
thank you!
