### ISSUE TITLE
Not working link on manifold twitter

### ISSUE THREAD

**Issue by dynsky** [manifoldfinance/support#9]
Openmev.org link not working on manifold twitter
![Screenshot_20220904-091059_Chrome](https://user-images.githubusercontent.com/96447749/188316907-925291aa-37d0-4c5a-8c8f-7031d27d42de.jpg)
![Screenshot_20220904-091106_Chrome](https://user-images.githubusercontent.com/96447749/188316918-93e86603-296f-4eb6-8869-3c8ca9297917.jpg)

**Comment by sambacha** [comment]
we are in the process of updating some DNS endpoints thanks for reporting this it should be resolved
